---
title: "Life Expectancy"
author: "Callum & Gugo"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)     # for data cleaning and plotting
library(gardenR)       # for Lisa's garden data
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(palmerpenguins)# for Palmer penguin data
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
theme_set(theme_minimal())
```


```{r}
life_expectancy <- read_csv("Life Expectancy Data.csv")
```

RQ: How has life expectancy changed over the years and what factors have contributed to this change?

I. Intro & Background

- Bullshit.

II. Data

- Source?
- Variables used.

III. Introductory Graph.

- Average life expectancy by the year.

IV. Map showing life expectancy by country.

V. Effect of aclhohol consumption on life expectancy.

VI. 

```{r, fig.width=7}
life_expectancy_1 <- life_expectancy %>% 
  select(Country, `Life expectancy`, Year) %>% 
  filter(Country %in% c("Russian Federation", "United Kingdom of Great Britain and Northern Ireland", "Japan", "Canada", "United States of America", "Mexico", "Brazil", "Argentina", "Peru", "Australia", "New Zealand", "Indonesia", "Swaziland", "Central African Republic", "Egpyt")) %>% 
  drop_na(Country, `Life expectancy`) %>% 
  group_by(Country, Year)
  
  life_expectancy_1 %>% 
  ggplot(aes(x = Year, y = `Life expectancy`, color = Country)) +
  geom_line() +
    labs(title = "Life Expectancies by Country from 2000 t0 2015", x = "Year", y = "Life Expectancy") +
    theme_classic()
```

